trigger: ["master"]
pr: ["master"]

resources:
  repositories:
    - repository: templates
      type: github
      name: xoac/rust-azure-pipelines
      endpoint: PiplinesTemplate


jobs:
# Check formatting
- template: ci/rustfmt.yml@templates
  parameters:
    name: rustfmt

# Test crate
- template: ci/test-stable.yml@templates
  parameters:
    name: cargo_test
    displayName: Test cargo
    cross: true # Test on Windows and macOS

# Cargo check
- template: ci/cargo-check.yml@templates
  parameters:
    name: cargo_check
    displayName: Cargo check
    rust: stable

# List of supported targets is available here: https://github.com/rust-embedded/cross#supported-targets
- template: ci/cargo-cross.yml@templates
  parameters:
        name: cross
        rust: stable
        check_targets:
                - i686-unknown-freebsd
                # - thumbv7em-none-eabihf # bare metal require no_std! future enable.
        test_targets:
                - mips-unknown-linux-musl
                - armv7-unknown-linux-musleabihf

# This represents the minimum Rust version supported.
# Tests are not run as tests may require newer versions of rust.
- template: ci/check-minrust.yml@templates
  parameters:
    name: minrust
    rust_version: 1.31.0 # The 2018 edition

# Deploy doc
# TODO you need to modify git parameters and specify variable in pipelin. See README.md
- template: ci/deploy-docs.yml@templates
  parameters:
    dependsOn:
      - rustfmt
      - cargo_test
      - cargo_check
      - cross
    git:
     user: xoac
     email: sylwesterrapala@outlook.com
     repo: https://github.com/xoac/rust-azure-pipelines/
