trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

resources:
  repositories:
    - repository: rust_pipelines
      type: github
      name: xoac/rust-azure-pipelines
      ref: refs/tags/v0.1.0-alpha.2
      #ref: refs/head/develop ## TODO you may want to change it to refs/tags/TAG_NAME.
      endpoint: PipelinesTemplates

stages: 
- stage: check
  displayName: "Quick checks"
  jobs:
  - template: ci/scenarios/check.yml@rust_pipelines
    parameters:
      cargo-check: true
      cargo-check-nigtly: true
      cargo-clippy: true
      rustfmt: true

- stage: test
  displayName: "Multi OS native tests"
  jobs:
  - template: ci/scenarios/test.yml@rust_pipelines
    parameters:
      min_rust_supported: 1.31

# This stage allow to easy test your crate using cross project. 
# Supported targets: https://github.com/rust-embedded/cross#supported-targets
- stage: embedded
  displayName: "Cross check and tests"
  dependsOn:
    - check
  jobs:
  - template: ci/scenarios/embeeded.yml@rust_pipelines
    parameters:
      checks:
        - target: mips-unknown-linux-musl
          name: cross_chcek_i686_unknown_freebsd 
        - target: aarch64-unknown-linux-gnu
          name: cross_check_aarch64_unknown_linux_gnu
      tests:
        - target: i686-unknown-linux-gnu
          name: cross_test_i686_unknown_linux_gnu

# This stage build binarries - you can deploy them in next stage
- stage: build
  displayName: "Builds"
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
  dependsOn:
    - embedded
    - test 
  jobs:
  - template: ci/scenarios/builds.yml@rust_pipelines 
    parameters:
      artifactName: target

- stage: deploy
  displayName: "Deploys"
  dependsOn:
    - build
  jobs:
  # Deploy doc
  - template: ci/scenarios/github/deploy-doc.yml@rust_pipelines
    parameters:
     branch: develop
     job_name: github_deploy_doc
     github:
      user: xoac
      email: sylwesterrapala@outlook.com
      repo: https://github.com/xoac/rust-azure-pipelines/
 
  - template: ci/scenarios/github/release.yml@rust_pipelines
    parameters:
      job_condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
      gitHubConnection: PipelinesTemplates 
