trigger: ["master"]
pr: ["master"]

resources:
  repositories:
    - repository: templates
      type: github
      name: xoac/rust-azure-pipelines
      ref: refs/heads/master ## TODO you may want to change it to refs/tags/TAG_NAME. 
      endpoint: PipelinesTemplates

jobs:
# Check formatting
- template: ci/rustfmt.yml@templates
  parameters:
    name: rustfmt

# Test stable
- template: ci/test.yml@templates
  parameters:
    name: cargo_test_stable
    displayName: Test cargo
    cross: true # Test on Windows and macOS

# Test nightly
- template: ci/test.yml@templates
  parameters:
    name: cargo_test_nightly
    displayName: Test cargo
    rust_version: nightly

# Cargo check
- template: ci/cargo-check.yml@templates
  parameters:
    name: cargo_check
    displayName: Cargo check

# List of supported targets is available here: https://github.com/rust-embedded/cross#supported-targets
- template: ci/cargo-cross.yml@templates
  parameters:
        name: cross
        rust_version: stable # You can specify here beta nightly or even 1.31
        check_targets:
                - i686-unknown-freebsd
                # - thumbv7em-none-eabihf # bare metal require no_std! future enabled.
        test_targets:
                - mips-unknown-linux-gnu
                - armv7-unknown-linux-musleabihf

# This represents the minimum Rust version supported.
# Tests are not run as tests may require newer versions of rust.
- template: ci/check-minrust.yml@templates
  parameters:
    name: minrust
    rust_version: 1.31.0 # The 2018 edition

# Deploy doc
# TODO you need to modify git parameters and specify variable in pipeline. See [README.md](https://github.com/xoac/rust-azure-pipelines/blob/master/README.md)
- template: ci/deploy-docs.yml@templates
  parameters:
    dependsOn:
      - rustfmt
      - cargo_test_stable
      - cargo_check
      - cross
    git:
     user: xoac
     email: sylwesterrapala@outlook.com
     repo: https://github.com/xoac/rust-azure-pipelines/

# Release binary
- template : ci/release.yml
  parameters:
    displayName: Realese
